### ISSUE TITLE
The diagram is shifted to the left

### ISSUE THREAD

**Issue by ParticleCat** [JP-Ellis/tikz-feynman#25]
Thanks for the awesome package !

However, I got some problem with the plots.
When I follow the examples, the diagrams are all squeezed to the left.
Which looks like
[Untitled.pdf](https://github.com/JP-Ellis/tikz-feynman/files/191800/Untitled.pdf)

How should I adjust the package to make it normal ?

**Comment by JP-Ellis** [comment]
I'm glad you like Ti*k*Z-Feynman!

The error you are having is most likely because you are generating the diagram with pdfLaTeX or XeLaTeX.  If you want the vertices to be placed automatically, Ti*k*Z-Feynman requires LuaTeX in order to have access to the Lua backend.

Normally, this should have actually come up as warnings in the log file.  If it hasn't then please let me know.

**Comment by ParticleCat** [comment]
Thanks ! ^_^
