### ISSUE TITLE
How do I force several nodes on a horizontal line?

### ISSUE THREAD

**Issue by linwaytin** [JP-Ellis/tikz-feynman#26]
Hi,

I must say this package is amazing! It makes things much easier than other packages. 

I have several nodes and I want to put them on a horizontal line. If there are only two, I know I can use the option `horizontal=a to b`. But I actually have more than 2. Is there any easy way to handle this?

Thank you,
Wei

**Comment by JP-Ellis** [comment]
I'm glad you find Ti*k*Z-Feynman useful!

You can use the `layered layout` option to produce straight lines.  The default `spring layout` is much more optimized for layouts that branch out more, whereas the `layered layout` imposes a much more rigid structure.

For example:
```latex
\documentclass[tikz, border=10pt, convert]{standalone}

\usepackage[compat=1.1.0]{tikz-feynman}

\begin{document}
\feynmandiagram [layered layout, horizontal=a to b] {
  a -- [boson] b -- [fermion] c -- [gluon] d,
};
\end{document}
```
produces:
![output](https://cloud.githubusercontent.com/assets/3196162/14663363/96975990-0703-11e6-8d3b-e42df9f37ce6.png)

The documentation has examples of more complicated diagrams which also use the `layered layout`, and otherwise you can also have a look at the [TikZ Manual](http://mirrors.ctan.org/graphics/pgf/base/doc/pgfmanual.pdf) for a more thorough explanation of the `layered layout` algorithm.

**Comment by linwaytin** [comment]
Thank you for your answer.

In fact, my problem is a little tricky. I need to put some self-energy lines on the horizontal line.
```
\documentclass[tikz, border=10pt, convert]{standalone}
\usepackage[compat=1.1.0]{tikz-feynman}

\begin{document}
\feynmandiagram [layered layout, horizontal=b to c] {
  a -- [fermion] b -- [fermion] c -- [fermion] d,
  e -- [scalar] b,
  e -- [scalar] c,
};
\end{document}
```
I want to make a, b, c, and d on a horizontal line. The above code can't do that.

**Comment by JP-Ellis** [comment]
Is that what you want?

```latex
\documentclass[tikz, border=10pt, convert]{standalone}
\usepackage[compat=1.1.0]{tikz-feynman}

\begin{document}
\feynmandiagram [layered layout, horizontal=b to c] {
  a -- [fermion] b -- [fermion] c -- [fermion] d,
  c -- [scalar, half left] b,
};
\end{document}
```
![26](https://cloud.githubusercontent.com/assets/3196162/14758949/5132c846-0954-11e6-87fc-7557f31d4b6e.png)

**Comment by linwaytin** [comment]
Not exactly. I want a vertex and two straight edges. It seems I have to specify positions of all points?

**Comment by JP-Ellis** [comment]
I'm not sure why you want a vertex there, unless it attaches to other things.  Anyway, it probably is easiest to add this extra vertex manually as follows:

```latex
\documentclass[tikz, border=10pt, convert]{standalone}
\usepackage[compat=1.1.0]{tikz-feynman}

\begin{document}
\begin{tikzpicture}
  \begin{feynman}
    \diagram [layered layout, horizontal=b to c] {
      a -- [fermion] b -- [fermion] c -- [fermion] d,
    };
    \vertex (s) at ($(b)!0.5!(c) - (0, 1cm)$);
    \draw [scalar] (b) -- (s) -- (c);
  \end{feynman}
\end{tikzpicture}
\end{document}
```
![26](https://cloud.githubusercontent.com/assets/3196162/14765144/7523b044-0a17-11e6-90ff-2e9b2c839bd5.png)

**Comment by linwaytin** [comment]
This graph is used in my research. Indeed, it is unusual.

Thank you so much for answering my question.
