### ISSUE TITLE
Internal vertex label

### ISSUE THREAD

**Issue by pseth** [JP-Ellis/tikz-feynman#31]
Hello,

Thanks for the package, it is great!
I am trying to create a very simple bubble diagram where I wish to give the (internal) vertices labels that appear below a dot. However, I can't seem to get this to work. I can get either the dot, or the label name in place of the dot (which, as you point out in the notes, breaks the lines).

I have tried both of the following thinking this API seemed reasonable:

```
\feynmandiagram [layered layout, horizontal=a to b] {
    a [particle={$t_1$},dot] -- [fermion, half left] b [dot]
    -- [fermion, half left] a,
};  
 
\begin{tikzpicture}
  \begin{feynman}
    \vertex[dot] (a) {$t_1$};
    \vertex[right= of a, dot] (b) {$t_2$};
    \diagram* {
        (a) -- [fermion, half left] (b),
        (b) -- [fermion, half left] (a),
    };
  \end{feynman}
\end{tikzpicture}
```

However, neither works. In the second example, the dot simply becomes bigger. Is there a way to do this?

Thanks!

**Comment by JP-Ellis** [comment]
Hi,

I'm glad you're finding Ti*k*Z-Feynman useful!

As you have noticed, the `particle` and `dot` style are mutually exclusive because they modify the shape of the vertex itself.  If you want an annotated dot, you can use the `label` directive:

```latex
\documentclass[tikz, border=5pt]{standalone}

\usepackage[compat=1.1.0]{tikz-feynman}

\begin{document}
\feynmandiagram [layered layout, horizontal=a to b] {
  a [dot, label=180:\(t_{1}\)]
  -- [fermion, half left] b [dot, label=0:\(t_{2}\)]
  -- [fermion, half left] a,
};  

\begin{tikzpicture}
  \begin{feynman}
    \vertex[dot, label=180:\(t_{1}\)] (a) {};
    \vertex[right=of a, dot, label=0:\(t_{2}\)] (b) {};
    \diagram* {
        (a) -- [fermion, half left] (b),
        (b) -- [fermion, half left] (a),
    };
  \end{feynman}
\end{tikzpicture}
\end{document}
```

![pseth-1](https://cloud.githubusercontent.com/assets/3196162/17576580/8687f3b8-5fb7-11e6-857b-65eeeeb481a3.png)

I hope that helps!

**Comment by pseth** [comment]
Brilliant, thanks!

**Comment by g0chan** [comment]
Hi JP! I'm loving tikz and Feynman. Super useful. I was hoping you could help me with something. I'm growing a little frustrated because I can't quite get this diagram to work:

`\begin{tikzpicture}
\begin{feynman}
\vertex (a) {\(p_1\)};
\vertex[below right=of a](a1);
\vertex[below=1in of a1](b1);
\vertex[below left=of b1](b){\(p_2\)};
\vertex[right=1in of a1](c1);
\vertex[above right=of c1](c){\(p_3\)};
\vertex[right=1in of b1](d1);
\vertex[below right=of d1](d){\(p_4\)}; 
\diagram* {
	(a) -- [fermion] (a1) ,
	(b) -- [fermion] (b1),
	(c1) -- [fermion] (c),
	(d1) -- [fermion] (d),
	(a1) -- [fermion, half left] (c1)
	(c1) -- [fermion, half left] (d1)
	(d1) -- [fermion, half left] (b1)
	(b1) -- [fermion, half left] (a1)
};
\end{feynman}
\end{tikzpicture}`

Which is coming out like a four leaf clover. I'm trying to create the diagram in my paper (Fig. 1): https://arxiv.org/pdf/1801.08627.pdf

A past group member made the pic but didn't use tikz feynman so I'm trying to do it here. If you could help in anyway I'd really appreciate it. Thanks!
