### ISSUE TITLE
Vector boson scattering vertex

### ISSUE THREAD

**Issue by gpinnaan** [JP-Ellis/tikz-feynman#36]
When I draw a diagram with a 4 line vertex the line are always horizontal or vertical.

\feynmandiagram [] {
  i1 -- [boson ,  edge label=\(W^+\)] a -- [photon,  edge label=\(W^-\)] i2,
  f1 -- [photon,  edge label=\(Z\)]  a -- [photon,  edge label=\(Z\)] f2,
};
Is there any simple way to have diagonal lines instead?

thanks

**Comment by JP-Ellis** [comment]
You can use the `vertical=⟨node⟩ to ⟨node⟩` (and similarly `horizontal` and the primed counterparts) key to change the orientation of the diagram.  As I mention in the documentation, the two vertices need not be neighbours, so you can have `horizontal=i1 to i2`.

There are other issues with your example though.  You have `edge label=(W^+)`, but I'm not sure you really want this to be parenthesised.  Did you intend to have a math environment, because this requires `\(…\)`—note the backslash `\` before the opening and closing parenthesis.  I'm also not sure why you have the empty `[]` after `\feynmandiagram`.  In LaTeX, `[]` is conventionally used to indicate optional arguments, and if no optional arguments are required, they can be omitted. 

Is this what you want:

```
\RequirePackage{luatex85}
\documentclass[border=10pt]{standalone}

\usepackage[compat=1.1.0]{tikz-feynman}

\begin{document}
\feynmandiagram [vertical'=i1 to i2] {
  i1 [particle=\(W^{+}\)] -- [boson] a -- [boson] i2 [particle=\(W^{-}\)],
  f1 [particle=\(Z\)] -- [boson] a -- [boson] f2 [particle=\(Z\)],
};
\end{document}
```

![gpinnaan-1](https://cloud.githubusercontent.com/assets/3196162/20508533/5c28d3da-b0b6-11e6-9738-6b82cc4a1736.png)
